---

- name: install system packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - build-essential
    - git
    - python-dev
    - python-pip
    - htop
    - itop
    - curl
    - wget
  sudo: yes

- name: set timezone to UTC
  file: src=/usr/share/zoneinfo/UTC path=/etc/localtime state=link force=yes
  sudo: yes
  notify: restart cron