# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "devbox" do |devbox|
    devbox.vm.network :forwarded_port, guest: 8000, host: 8000
    devbox.vm.network :forwarded_port, guest: 80, host: 80
    devbox.vm.network :private_network, ip: "192.168.33.12"

    devbox.vm.synced_folder "../", "/opt/jobber/"

    devbox.vm.hostname = "jobber.dev"
  end

end
